// Lista completa de 138 géneros — fuente: docs/RABAT_esquema_de_datos.md Apéndice A
export const GENRES = [
  'Alternative',
  'Alternative / College Rock',
  'Alternative / Emo',
  'Alternative / Goth Rock',
  'Alternative / Grunge',
  'Alternative / Indie Rock',
  'Alternative / New Wave',
  'Alternative / Punk',
  'Blues',
  'Blues / Acoustic Blues',
  'Blues / Chicago Blues',
  'Blues / Classic Blues',
  'Blues / Contemporary Blues',
  'Blues / Country Blues',
  'Blues / Delta Blues',
  'Blues / Electric Blues',
  "Children's Music",
  "Children's Music / Lullabies",
  "Children's Music / Sing-Along",
  'Country',
  'Country / Alternative Country',
  'Country / Americana',
  'Country / Bluegrass',
  'Country / Contemporary Bluegrass',
  'Country / Contemporary Country',
  'Country / Country Gospel',
  'Country / Honky Tonk',
  'Country / Outlaw Country',
  'Country / Traditional Bluegrass',
  'Country / Traditional Country',
  'Country / Urban Cowboy',
  'Dance',
  'Dance / Afro House',
  'Dance / Breakbeat',
  'Dance / Drum & Bass/Jungle',
  'Dance / Hardstyle/Hardcore',
  'Dance / House',
  'Dance / Techno',
  'Dance / Trance',
  'Dance / UK Garage',
  'Easy Listening / Lounge',
  'Easy Listening / Swing',
  'Electronic',
  'Electronic / Amapiano',
  'Electronic / Ambient',
  'Electronic / Bass',
  'Electronic / Downtempo',
  'Electronic / Dubstep',
  'Electronic / Electronica',
  'Electronic / Funk Carioca/Baile Funk',
  'Electronic / IDM/Experimental',
  'Electronic / Industrial',
  'Electronic / Levant Electronic',
  'Electronic / Maghreb Electronic',
  'Folk',
  'Hip Hop/Rap',
  'Hip Hop/Rap / Alternative Rap',
  'Hip Hop/Rap / Dirty South',
  'Hip Hop/Rap / East Coast Rap',
  'Hip Hop/Rap / Gangsta Rap',
  'Hip Hop/Rap / Hardcore Rap',
  'Hip Hop/Rap / Hip-Hop',
  'Hip Hop/Rap / Latin Rap',
  'Hip Hop/Rap / Old School Rap',
  'Hip Hop/Rap / Rap',
  'Hip Hop/Rap / Trap',
  'Hip Hop/Rap / UK Hip Hop',
  'Hip Hop/Rap / Underground Rap',
  'Hip Hop/Rap / West Coast Rap',
  'Holiday',
  'Holiday / Christmas',
  "Holiday / Christmas: Children's",
  'Holiday / Christmas: Classic',
  'Holiday / Christmas: Country',
  'Holiday / Christmas: Jazz',
  'Holiday / Christmas: Modern',
  'Holiday / Christmas: Pop',
  'Holiday / Christmas: R&B',
  'Holiday / Christmas: Religious',
  'Holiday / Christmas: Rock',
  'Holiday / Easter',
  'Holiday / Halloween',
  'Holiday / Thanksgiving',
  'Inspirational',
  'Jazz',
  'Jazz / Avant-Garde Jazz',
  'Jazz / Big Band',
  'Jazz / Bop',
  'Jazz / Bossa Nova',
  'Jazz / Contemporary Jazz',
  'Jazz / Cool',
  'Jazz / Crossover Jazz',
  'Jazz / Dixieland',
  'Jazz / Easy Listening',
  'Jazz / Fusion',
  'Jazz / Hard Bop',
  'Jazz / Latin Jazz',
  'Jazz / Mainstream Jazz',
  'Jazz / Ragtime',
  'Jazz / Smooth Jazz',
  'Jazz / Trad Jazz',
  'Latin',
  'Latin / Alternativo & Rock Latino',
  'Latin / Baladas y Boleros',
  'Latin / Contemporary Latin',
  'Latin / Flamenco',
  'Latin / Pop Latino',
  'Latin / Raíces',
  'Latin / Reggaeton y Hip-Hop',
  'Latin / Regional Mexicano',
  'Latin / Salsa y Tropical',
  'New Age',
  'New Age / Meditation',
  'New Age / Travel',
  'New Age / Yoga',
  'Pop',
  'Pop / Adult Contemporary',
  'Pop / Alternative Pop',
  'Pop / Britpop',
  'Pop / Indie Pop',
  'Pop / Pop/Rock',
  'Pop / Singer/Songwriter',
  'Pop / Soft Rock',
  'Pop / Teen Pop',
  'R&B/Soul',
  'R&B/Soul / Contemporary R&B',
  'R&B/Soul / Disco',
  'R&B/Soul / Doo Wop',
  'R&B/Soul / Funk',
  'R&B/Soul / Motown',
  'R&B/Soul / Neo-Soul',
  'R&B/Soul / Soul',
  'Reggae',
  'Reggae / Dub',
  'Reggae / Lovers Rock',
  'Reggae / Modern Dancehall',
  'Reggae / Roots Reggae',
  'Reggae / Ska',
  'Rock',
  'Rock / Adult Alternative',
  'Rock / American Trad Rock',
  'Rock / Arena Rock',
  'Rock / Blues-Rock',
  'Rock / British Invasion',
  'Rock / Death Metal/Black Metal',
  'Rock / Glam Rock',
  'Rock / Hair Metal',
  'Rock / Hard Rock',
  'Rock / Heavy Metal',
  'Rock / Jam Bands',
  'Rock / Prog-Rock/Art Rock',
  'Rock / Psychedelic',
  'Rock / Rock & Roll',
  'Rock / Rockabilly',
  'Rock / Roots Rock',
  'Rock / Southern Rock',
  'Rock / Surf',
  'Rock / Tex-Mex',
  'Soundtrack',
  'Soundtrack / Foreign Cinema',
  'Soundtrack / Musicals',
  'Soundtrack / Original Score',
  'Soundtrack / TV Soundtrack',
  'Soundtrack / Video Game',
  'Vocal',
  'Vocal / Standards',
  'Vocal / Traditional Pop',
  'Vocal / Vocal Jazz',
  'Vocal / Vocal Pop',
  'World',
  'World / Afro Pop',
  'World / Afrobeats',
  'World / Christian & Gospel',
  'World / Klezmer',
  'World / Polka',
] as const;

export type Genre = (typeof GENRES)[number];